const fs = require("fs");
let code = fs.readFileSync("app/layout.tsx", "utf8");

const metadataInsert = `export const metadata: Metadata = {
  metadataBase: new URL("https://trappedintoarchitecture.com"),
  title: {
    default: "Trapped Into Architecture",
    template: "%s | Trapped Into Architecture",
  },
  description: "Discover architecture firms, internships, remote jobs, and career resources. The ultimate platform for architecture professionals and students.",
  openGraph: {
    title: "Trapped Into Architecture",
    description: "Discover architecture firms, internships, remote jobs, and career resources.",
    url: "https://trappedintoarchitecture.com",
    siteName: "Trapped Into Architecture",
    images: [
      {
        url: "/og-image.jpg", // Fallback image if exists, else it will gracefully fallback
        width: 1200,
        height: 630,
      }
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Trapped Into Architecture",
    description: "Discover architecture firms, internships, remote jobs, and career resources.",
  },
};`;

code = code.replace(
  `export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};`,
  metadataInsert
);

fs.writeFileSync("app/layout.tsx", code);

